In [77]:
class StandardClass:
    total_students = 0  # 클래스 변수: 전체 학생 수

    def __init__(self, class_name):
        self.class_name = class_name  # 반 이름
        self.students = []  # 학생 리스트

    def __str__(self):
        """매직 메서드: 반 상태 출력"""
        if not self.students:
            return f"{self.class_name} 반에는 현재 학생이 없습니다."
        student_list = "\n".join([f"{i+1}. {s['name']} (나이: {s['age']}, 귀찮음 횟수: {s['bother_count']})"
                                for i, s in enumerate(self.students)])
        return f"{self.class_name} 반 학생 목록:\n{student_list}"

    def add_student(self, name, age):
        """인스턴스 메서드: 학생 추가"""
        self.students.append({"name": name, "age": age, "bother_count": 0})
        StandardClass.total_students += 1
        print(f"{name} 학생이 {self.class_name} 반에 추가되었습니다!")

    def remove_student(self, name):
        """인스턴스 메서드: 학생 삭제"""
        for student in self.students:
            if student["name"] == name:
                self.students.remove(student)
                StandardClass.total_students -= 1
                print(f"{name} 학생이 {self.class_name} 반에서 삭제되었습니다!")
                return
        print(f"{name} 학생을 찾을 수 없습니다.")

    def bother_teacher(self, name, max_bother=5):
        """특정 학생의 귀찮음 횟수를 증가시키고, 경고를 출력"""
        for student in self.students:
            if student["name"] == name:
                student["bother_count"] += 1
                if student["bother_count"] > max_bother:
                    print(f"{name} 학생은 너무 많이 귀찮게 했습니다! (총 {student['bother_count']}회)")
                else:
                    print(f"{name} 학생이 튜터님을 귀찮게 했습니다! (총 {student['bother_count']}회)")
                return
        print(f"{name} 학생을 찾을 수 없습니다.")

    def reset_bother_counts(self):
        """인스턴스 메서드: 모든 학생의 귀찮음 횟수 초기화"""
        for student in self.students:
            student["bother_count"] = 0
        print("다 나가주세요! 혼자 있고 싶으니까...")
        print("모든 학생의 귀찮음 횟수가 초기화되었습니다.")

    @classmethod
    def get_total_students(cls):
        """클래스 메서드: 전체 학생 수 반환"""
        return f"전체 학생 수: {cls.total_students}명"

    @staticmethod
    def calculate_total_bother(students):
        """스태틱 메서드: 반 전체 귀찮음 횟수 계산"""
        return sum(student["bother_count"] for student in students)

    @staticmethod
    def find_top_botherers(students, top_n=1):
        """스태틱 메서드: 상위 귀찮은 학생 조회"""
        if not students:
            return "학생이 없습니다."
        # 귀찮음 횟수를 기준으로 정렬
        sorted_students = sorted(students, key=lambda x: x["bother_count"], reverse=True)
        return sorted_students[:top_n]
    




    if __name__ == "__main__":
    # 스탠다드반 생성
        class1 = StandardClass("스탠다드반")
    
    
    # 학생 추가
    class1.add_student("곽종태", 20)
    class1.add_student("김모세", 20)
    class1.add_student("김용수", 20)
    class1.add_student("노호성", 21)
    class1.add_student("박민지", 21)
    class1.add_student("박종관", 21)
    class1.add_student("백명남", 22)
    class1.add_student("오세은", 22)
    class1.add_student("유종열", 22)
    class1.add_student("이수관", 23)
    class1.add_student("이현지", 23)
    class1.add_student("정지웅", 23)
    class1.add_student("조수현", 24)
    class1.add_student("최수빈", 24)
    class1.add_student("최정은", 24)

곽종태 학생이 스탠다드반 반에 추가되었습니다!
김모세 학생이 스탠다드반 반에 추가되었습니다!
김용수 학생이 스탠다드반 반에 추가되었습니다!
노호성 학생이 스탠다드반 반에 추가되었습니다!
박민지 학생이 스탠다드반 반에 추가되었습니다!
박종관 학생이 스탠다드반 반에 추가되었습니다!
백명남 학생이 스탠다드반 반에 추가되었습니다!
오세은 학생이 스탠다드반 반에 추가되었습니다!
유종열 학생이 스탠다드반 반에 추가되었습니다!
이수관 학생이 스탠다드반 반에 추가되었습니다!
이현지 학생이 스탠다드반 반에 추가되었습니다!
정지웅 학생이 스탠다드반 반에 추가되었습니다!
조수현 학생이 스탠다드반 반에 추가되었습니다!
최수빈 학생이 스탠다드반 반에 추가되었습니다!
최정은 학생이 스탠다드반 반에 추가되었습니다!


In [78]:
# 반 정보 출력
print(class1)

스탠다드반 반 학생 목록:
1. 곽종태 (나이: 20, 귀찮음 횟수: 0)
2. 김모세 (나이: 20, 귀찮음 횟수: 0)
3. 김용수 (나이: 20, 귀찮음 횟수: 0)
4. 노호성 (나이: 21, 귀찮음 횟수: 0)
5. 박민지 (나이: 21, 귀찮음 횟수: 0)
6. 박종관 (나이: 21, 귀찮음 횟수: 0)
7. 백명남 (나이: 22, 귀찮음 횟수: 0)
8. 오세은 (나이: 22, 귀찮음 횟수: 0)
9. 유종열 (나이: 22, 귀찮음 횟수: 0)
10. 이수관 (나이: 23, 귀찮음 횟수: 0)
11. 이현지 (나이: 23, 귀찮음 횟수: 0)
12. 정지웅 (나이: 23, 귀찮음 횟수: 0)
13. 조수현 (나이: 24, 귀찮음 횟수: 0)
14. 최수빈 (나이: 24, 귀찮음 횟수: 0)
15. 최정은 (나이: 24, 귀찮음 횟수: 0)


In [98]:
# 선생님 귀찮게 하기
class1.bother_teacher("조수현")
class1.bother_teacher("박민지")
class1.bother_teacher("최수빈")

조수현 학생이 튜터님을 귀찮게 했습니다! (총 1회)
박민지 학생이 튜터님을 귀찮게 했습니다! (총 1회)
최수빈 학생이 튜터님을 귀찮게 했습니다! (총 1회)


In [95]:
# 반 전체 귀찮음 횟수 계산
total_bother = StandardClass.calculate_total_bother(class1.students)
print(f"반 전체 귀찮음 횟수: {total_bother}회")

반 전체 귀찮음 횟수: 22회


In [96]:
# 상위 귀찮음 기록자 출력
top_botherers = StandardClass.find_top_botherers(class1.students, top_n=2)
print("상위 귀찮음 기록자:")
for student in top_botherers:
    print(f"{student['name']} - 귀찮음 횟수: {student['bother_count']}회")

상위 귀찮음 기록자:
조수현 - 귀찮음 횟수: 10회
박민지 - 귀찮음 횟수: 6회


In [97]:
# 귀찮음 횟수 초기화
class1.reset_bother_counts()
print(class1)

다 나가주세요! 혼자 있고 싶으니까...
모든 학생의 귀찮음 횟수가 초기화되었습니다.
스탠다드반 반 학생 목록:
1. 곽종태 (나이: 20, 귀찮음 횟수: 0)
2. 김모세 (나이: 20, 귀찮음 횟수: 0)
3. 김용수 (나이: 20, 귀찮음 횟수: 0)
4. 노호성 (나이: 21, 귀찮음 횟수: 0)
5. 박민지 (나이: 21, 귀찮음 횟수: 0)
6. 박종관 (나이: 21, 귀찮음 횟수: 0)
7. 백명남 (나이: 22, 귀찮음 횟수: 0)
8. 오세은 (나이: 22, 귀찮음 횟수: 0)
9. 유종열 (나이: 22, 귀찮음 횟수: 0)
10. 이수관 (나이: 23, 귀찮음 횟수: 0)
11. 이현지 (나이: 23, 귀찮음 횟수: 0)
12. 정지웅 (나이: 23, 귀찮음 횟수: 0)
13. 조수현 (나이: 24, 귀찮음 횟수: 0)
14. 최수빈 (나이: 24, 귀찮음 횟수: 0)
15. 최정은 (나이: 24, 귀찮음 횟수: 0)


In [99]:
class StandardClass:
    total_students = 0  # 전체 학생 수를 저장하는 클래스 변수

    def __init__(self):
        self.class_name = "스탠다드반"  # 반 이름 고정
        self.students = []  # 학생 정보를 저장할 리스트 초기화

    def __str__(self):
        # 학생 리스트가 비어 있는지 확인하여 메시지 반환
        if not self.students:
            return f"{self.class_name} 반에는 현재 학생이 없습니다."
        # 학생 정보를 포맷팅하여 문자열로 반환
        return "\n".join(
            [f"{i+1}. {s['name']} (나이: {s['age']}, 귀찮음: {s['bother_count']})" for i, s in enumerate(self.students)]
        )

    def add_student(self, name, age):
        # 학생 정보를 딕셔너리 형태로 추가
        self.students.append({"name": name, "age": age, "bother_count": 0})
        # 클래스 변수로 전체 학생 수 증가
        StandardClass.total_students += 1

    def bother_teacher(self, name, max_bother=5):
        # 학생 리스트를 순회하며 이름이 일치하는 학생 찾기
        for student in self.students:
            if student["name"] == name:
                student["bother_count"] += 1  # 귀찮음 횟수 증가
                if student["bother_count"] > max_bother:  # 최대 허용 횟수를 초과한 경우
                    print(f"{name} 학생은 너무 많이 귀찮게 했습니다! (총 {student['bother_count']}회)")
                else:
                    print(f"{name} 학생이 귀찮게 했습니다! (총 {student['bother_count']}회)")
                return
        # 이름이 없는 경우 메시지 출력
        print(f"{name} 학생을 찾을 수 없습니다.")

    def reset_bother_counts(self):
        # 학생 리스트를 순회하며 귀찮음 횟수를 초기화
        for student in self.students:
            student["bother_count"] = 0
        print("모두 나가주세요! 혼자 있고 싶으니까...")
        print("모든 귀찮음 횟수가 초기화되었습니다.")

if __name__ == "__main__":
    # 스탠다드반 생성
    class1 = StandardClass()

    # 학생 추가
    for name, age in [
        ("곽종태", 20), ("김모세", 20), ("김용수", 20), ("노호성", 21),
        ("박민지", 21), ("박종관", 21), ("백명남", 22), ("오세은", 22),
        ("유종열", 22), ("이수관", 23), ("이현지", 23), ("정지웅", 23),
        ("조수현", 24), ("최수빈", 24), ("최정은", 24)
    ]:
        class1.add_student(name, age)  # 이름과 나이를 사용해 학생 추가

    # 반 상태 출력
    print("\n<반 상태>")
    print(class1)  # 현재 반 상태 출력

    # 선생님 귀찮게 하기
    class1.bother_teacher("조수현")  # "조수현" 학생의 귀찮음 횟수 증가
    class1.bother_teacher("조수현")  # "조수현" 학생의 귀찮음 횟수 증가
    class1.bother_teacher("조수현")  # "조수현" 학생의 귀찮음 횟수 증가
    class1.bother_teacher("조수현")  # "조수현" 학생의 귀찮음 횟수 증가
    class1.bother_teacher("조수현")  # "조수현" 학생의 귀찮음 횟수 증가
    class1.bother_teacher("조수현")  # "조수현" 학생의 귀찮음 횟수 증가

    # 귀찮음 횟수 초기화
    class1.reset_bother_counts()  # 모든 학생의 귀찮음 횟수 초기화
    print("\n<귀찮음 횟수 초기화 후 반 상태>")
    print(class1)  # 초기화 후 반 상태 출력


<반 상태>
1. 곽종태 (나이: 20, 귀찮음: 0)
2. 김모세 (나이: 20, 귀찮음: 0)
3. 김용수 (나이: 20, 귀찮음: 0)
4. 노호성 (나이: 21, 귀찮음: 0)
5. 박민지 (나이: 21, 귀찮음: 0)
6. 박종관 (나이: 21, 귀찮음: 0)
7. 백명남 (나이: 22, 귀찮음: 0)
8. 오세은 (나이: 22, 귀찮음: 0)
9. 유종열 (나이: 22, 귀찮음: 0)
10. 이수관 (나이: 23, 귀찮음: 0)
11. 이현지 (나이: 23, 귀찮음: 0)
12. 정지웅 (나이: 23, 귀찮음: 0)
13. 조수현 (나이: 24, 귀찮음: 0)
14. 최수빈 (나이: 24, 귀찮음: 0)
15. 최정은 (나이: 24, 귀찮음: 0)
조수현 학생이 귀찮게 했습니다! (총 1회)
조수현 학생이 귀찮게 했습니다! (총 2회)
조수현 학생이 귀찮게 했습니다! (총 3회)
조수현 학생이 귀찮게 했습니다! (총 4회)
조수현 학생이 귀찮게 했습니다! (총 5회)
조수현 학생은 너무 많이 귀찮게 했습니다! (총 6회)
모두 나가주세요! 혼자 있고 싶으니까...
모든 귀찮음 횟수가 초기화되었습니다.

<귀찮음 횟수 초기화 후 반 상태>
1. 곽종태 (나이: 20, 귀찮음: 0)
2. 김모세 (나이: 20, 귀찮음: 0)
3. 김용수 (나이: 20, 귀찮음: 0)
4. 노호성 (나이: 21, 귀찮음: 0)
5. 박민지 (나이: 21, 귀찮음: 0)
6. 박종관 (나이: 21, 귀찮음: 0)
7. 백명남 (나이: 22, 귀찮음: 0)
8. 오세은 (나이: 22, 귀찮음: 0)
9. 유종열 (나이: 22, 귀찮음: 0)
10. 이수관 (나이: 23, 귀찮음: 0)
11. 이현지 (나이: 23, 귀찮음: 0)
12. 정지웅 (나이: 23, 귀찮음: 0)
13. 조수현 (나이: 24, 귀찮음: 0)
14. 최수빈 (나이: 24, 귀찮음: 0)
15. 최정은 (나이: 24, 귀찮음: 0)


In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, Normalizer

# 데이터 생성
X = np.array([[1, -1, 2],
              [2, 0, 0],
              [0, 1, -1]])

# 각각의 스케일링 적용
scalers = {
    "StandardScaler": StandardScaler(),
    "MinMaxScaler": MinMaxScaler(),
    "RobustScaler": RobustScaler(),
    "Normalizer": Normalizer()
}

# 결과 출력
for scaler_name, scaler in scalers.items():
    print(f"{scaler_name} 적용 결과:")
    print(scaler.fit_transform(X))
    print()

StandardScaler 적용 결과:
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]

MinMaxScaler 적용 결과:
[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]

RobustScaler 적용 결과:
[[ 0.         -1.          1.33333333]
 [ 1.          0.          0.        ]
 [-1.          1.         -0.66666667]]

Normalizer 적용 결과:
[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]

